### ISSUE TITLE
Attempt to edit a locked page should inform the user about last modification date

### ISSUE THREAD

**Issue by erdgeist** [hukl/cccms#13]
Damit man abschaetzen kann, ob der Hoschie da gerade noch dranne ist

**Comment by erdgeist** [comment]
… und bei der Gelegenheit sollte da gleich noch ein "Steal"-Button dranne

**Comment by hukl** [comment]
enhanced LockedByAnotherUser exception which now includes a message showing the last modified time.

Closed by 24265260b216e2be8d29d913c4d0396408981612
