### ISSUE TITLE
"Mehr.." Link in der Artikelliste /de/tags/..

### ISSUE THREAD

**Issue by CCC-zz** [hukl/cccms#34]
z.b. bei 
http://213.73.89.122:8080/de/tags/egk
sehe ich gar nicht, dass es sich um einen ganzen Artikel handelt.. dass man den Titel klicken muss, ist völlig unklar. Ein "Mehr ..." wäre sinnvoll.

**Comment by hukl** [comment]
Ich habe jetzt wie bei der Suche drübergeschrieben / angedeutet dass es sich um eine Liste von Seiten handelt die mit dem jeweiligen Tag getagged sind. Reicht dass vielleicht? Ich mag die mehr tags nicht so sehr. Falls es immernoch zu unklar ist bitte nochmal bescheid sagen
