### ISSUE TITLE
Text output stops after first paragraph

### ISSUE THREAD

**Issue by nitram2342** [hukl/cccms#47]
This is probably a bug. Please compare the ouput of

http://www.ccc.de/de/censorship
and
http://www.ccc.de/de/tags/chinese%20wall

**Comment by hukl** [comment]
Ich habe jetzt wie bei der Suche drübergeschrieben / angedeutet dass es sich um eine Liste von Seiten handelt die mit dem jeweiligen Tag getagged sind. Reicht dass vielleicht? Ich mag die mehr tags nicht so sehr. Falls es immernoch zu unklar ist bitte nochmal bescheid sagen

**Comment by nitram2342** [comment]
Ok, jetzt verstehe ich wie das mit den Tags gemeint ist. ;)
